run:
  modules-download-mode: readonly
  timeout: 5m

linters:
  disable-all: true
  enable:

    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - revive
    - ineffassign
    - typecheck

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-duplicates: true
  exclude-use-default: false
  max-issues-per-linter: 10
  max-same-issues: 3